version: '3'

networks:
  codeg-net:
    driver: bridge

services:
  codeg:
    image: nginx:stable-alpine
    container_name: codeg
    restart: unless-stopped
    ports:
      - '${APP_PORT:-8008}:80'
    volumes:
      - .:/var/www:delegated
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php
    networks:
      - codeg-net

  php:
    image: codeg.php:latest
    build:
      context: .
      dockerfile: server/php.dockerfile
      args:
        - APP_ENV=${APP_ENV}
    container_name: codeg-php
    restart: unless-stopped
    volumes:
      - .:/var/www:delegated
    networks:
      - codeg-net
